In [4]:
import numpy as np

In [10]:
# numpy vector (array)

a_list = [1, 2, 3]
a_np_list = np.array(a_list)

In [11]:
# numpy matrix

a_matrix = [[1, 2, 3], [4, 5, 6]]
np.array(a_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.arange(0, 11, 2) # range generator, last arg is stepsize

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros((2, 9)) # zero generator, single val for vec, 2 val for matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((3, 4)) # ones generator, works like zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0, 2, 5) # evenly spaced points between a and b; last arg is amt. of points

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
# id matrix w/numpy, pass in dimension (id is always square)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(2, 2) # 1d array/mat of nums sampled from uniform dist (between 0, 1)

array([[0.10424092, 0.61841399],
       [0.17150678, 0.51184041]])

In [25]:
np.random.randn(2, 2) # same thing but samples std. normal dist

array([[-2.63802398, -0.67938716],
       [-0.12812929,  1.20463398]])

In [30]:
np.random.randint(0, 100, 5) # random int between a, b, last arg. is amt to generate

array([99, 37,  5, 97, 94])

In [35]:
# reshape array into matrix, will error if not enough vals
arr = np.random.randint(0, 100, 30)
arr.reshape(3, 10)

array([[44, 18, 86, 18, 53, 61, 41, 88, 75,  5],
       [77, 24, 13, 46, 90, 89, 40, 86, 80, 73],
       [82,  3, 18, 37, 24, 71, 23, 33, 96, 49]])

In [45]:
# maxval and its index
arr = np.random.randint(0, 20, 10)
print(f"gen'd array: {arr}")
print(f"maxval: {arr.max()}")
print(f"maxval idx: {arr.argmax()}")

# also works with min!

gen'd array: [12  4 12 10 19  8 16 18 10  1]
maxval: 19
maxval idx: 4


In [46]:
# getting shape of arr
arr.shape

(10,)