In [3]:
import numpy as np

In [5]:
arr = np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# normal python indexing/slicing works!
arr[8]

8

In [15]:
arr[3:5]

array([3, 4])

In [16]:
arr[:5]

array([0, 1, 2, 3, 4])

In [17]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
print(f"og arr: {arr}")

# reassign slicing!
arr[:4] = 99

print(f"fuggled arr: {arr}")

og arr: [99 99 99 99  4  5  6  7  8  9 10]
fuggled arr: [99 99 99 99  4  5  6  7  8  9 10]


In [29]:
# slices are references; modifying them will mess with original arr!

arr = np.arange(0, 20)
print(f"og arr {arr}")

arr_slice = arr[:5]
arr_slice[:] = 99 # [:] just grabs everything
print(f"modded slice {arr_slice}")

print(f"og arr {arr}")

# numpy does this to avoid too much memory consumption for large arrays

og arr [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
modded slice [99 99 99 99 99]
og arr [99 99 99 99 99  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
# we need to copy manually!
arr_copy = arr[0:5].copy()
arr_copy

array([99, 99, 99, 99, 99])

In [43]:
mat = np.random.randint(0, 10, 20).reshape(5, 4)
mat

array([[3, 7, 8, 2],
       [7, 1, 2, 9],
       [1, 0, 6, 5],
       [7, 5, 7, 7],
       [9, 9, 3, 7]])

In [44]:
# can use doublebracks to index matrix [r][c]
mat[1][0]

7

In [45]:
# comma singlebrack notation (recommended!)
mat[1, 0]

7

In [49]:
# we can slice matrices too
# think of it as row selector and then col. selector
mat[:,0]

array([3, 7, 1, 7, 9])

In [53]:
arr = np.random.randint(0, 12, 15)
arr

array([ 1,  2,  7,  0,  4,  4,  9,  6, 11,  4,  3, 11,  4,  5,  0])

In [55]:
# conditional selection
# returns array of booleans in shape of given one,
# with true where val matches cond and false where it doesn't
gthan5 = arr > 5

In [56]:
# we can then pass bool array as idx, acting as a "mask"
# falses will be excluded
# trues will be included
arr[gthan5]

array([ 7,  9,  6, 11, 11])