In [6]:
import numpy as np

arr1 = np.arange(0, 4)
arr2 = np.random.randint(0, 5, 4)

print(arr1, arr2)

[0 1 2 3] [2 4 1 3]


In [17]:
# we can do arithmetic with arrays
# shapes must match!
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

# operands can be normal nums
print(arr1 + 32)
print(1 / (arr1 + 1))

# basically we can use array as a normal operand

# numpy doesnt shit itself on div by zero/errors, it just gives nan/inf
# 0/0 is nan
# 1/0 is inf (remember limits!)
print(arr1 / 0)

[2 5 3 6]
[-2 -3  1  0]
[0 4 2 9]
[0.   0.25 2.   1.  ]
[32 33 34 35]
[1.         0.5        0.33333333 0.25      ]
[nan inf inf inf]


/var/folders/zf/5lzc0nrs0b77909zc1hhspwc0000gn/T/ipykernel_19140/879253674.py:17: RuntimeWarning: divide by zero encountered in divide
  print(arr1 / 0)
/var/folders/zf/5lzc0nrs0b77909zc1hhspwc0000gn/T/ipykernel_19140/879253674.py:17: RuntimeWarning: invalid value encountered in divide
  print(arr1 / 0)


In [25]:
# universal array functions for fancier operations
np.sqrt(arr1)
np.exp(arr1)
np.max(arr) # same as arr.max()
np.sin(arr)
np.cos(arr)

# look at scipy docs for all!

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])